// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_ZH_URnt4PpHsV9Ysk2E5Xq-UeJvTsU',
    appId: '1:887770227572:web:07fbad07a18effd8234221',
    messagingSenderId: '887770227572',
    projectId: 'fir-tutorial-56dcd',
    authDomain: 'fir-tutorial-56dcd.firebaseapp.com',
    storageBucket: 'fir-tutorial-56dcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ3BQoSHe574wc3qMArPFQlknOw7XcVdA',
    appId: '1:887770227572:android:03b0003f8d36fd1b234221',
    messagingSenderId: '887770227572',
    projectId: 'fir-tutorial-56dcd',
    storageBucket: 'fir-tutorial-56dcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzeicVC-tpzsNpTQIOzEOCVpqa3kLGjI',
    appId: '1:887770227572:ios:5a78ff7bbceb5fbb234221',
    messagingSenderId: '887770227572',
    projectId: 'fir-tutorial-56dcd',
    storageBucket: 'fir-tutorial-56dcd.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzeicVC-tpzsNpTQIOzEOCVpqa3kLGjI',
    appId: '1:887770227572:ios:5a78ff7bbceb5fbb234221',
    messagingSenderId: '887770227572',
    projectId: 'fir-tutorial-56dcd',
    storageBucket: 'fir-tutorial-56dcd.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_ZH_URnt4PpHsV9Ysk2E5Xq-UeJvTsU',
    appId: '1:887770227572:web:6a1ac56e42b05307234221',
    messagingSenderId: '887770227572',
    projectId: 'fir-tutorial-56dcd',
    authDomain: 'fir-tutorial-56dcd.firebaseapp.com',
    storageBucket: 'fir-tutorial-56dcd.appspot.com',
  );
}
